// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prefer direct Postgres for CLI when set (Accelerate URLs are not valid for migrate/db push).
    url: process.env["DATABASE_DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
